AWSTemplateFormatVersion: "2010-09-09"
Description: RDS stack

Parameters:
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: The master user password
  DBGroupFamily:
    Type: String
    Default: aurora-postgresql14
    Description: The DB parameter group family

Resources:
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      AvailabilityZones:
        - eu-central-1a
      Engine: aurora-postgresql
      EngineVersion: 14.9
      MasterUsername: flyway
      MasterUserPassword: !Ref MasterUserPassword
      DatabaseName: library_service
      DBClusterIdentifier: library_service
      DBClusterParameterGroupName: !Ref DBClusterParameterGroup
      Port: 5432

  AuroraPrimaryDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: aurora-postgresql
      DBClusterIdentifier: !Ref RDSCluster
      DBInstanceClass: db.t4g.medium
      DBParameterGroupName: !Ref DBParameterGroup
      PubliclyAccessible: true

  DBClusterParameterGroup:
    Type: 'AWS::RDS::DBClusterParameterGroup'
    Properties:
      Family: !Ref DBGroupFamily
      Description: DB Cluster Parameter Group
      Parameters:
        log_autovacuum_min_duration: 0
        client_encoding: 'utf8'

  DBParameterGroup:
    Type: 'AWS::RDS::DBParameterGroup'
    Properties:
      Family: !Ref DBGroupFamily
      Description: DB Parameter Group
      Parameters:
        shared_preload_libraries: pg_stat_statements
        log_min_duration_statement: 1000
        log_connections: 1
        log_disconnections: 1
        log_lock_waits: 1
        log_temp_files: 0
        lc_messages: 'C'
        log_statement_stats: 0

Outputs:
  rdsClusterEndpoint:
    Value: !GetAtt RDSCluster.Endpoint.Address
    Description: RDS Cluster Endpoint
    Export:
      Name: library-service-cluster-endpoint
  rdsClusterEndpointPort:
    Value: !GetAtt RDSCluster.Endpoint.Port
    Description: RDS Cluster Endpoint Port
    Export:
      Name: library-service-cluster-endpoint-port